import { AlertCircle, Brain, Loader2, Send, Stethoscope } from "lucide-react"
import { useState } from "react"
import { api, getApiErrorMessage, isBackendUnavailable } from "../api/client.js"
import PageHeader from "../components/PageHeader.jsx"
import RiskEngineCard, { RuralAccessibilityToolbar, emergencyRiskFallback } from "../components/RiskEngineCard.jsx"
import StatusMessage from "../components/StatusMessage.jsx"

export default function SymptomChecker() {
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [fallback, setFallback] = useState(false)
  const [risk, setRisk] = useState(null)
  const [ruralMode, setRuralMode] = useState(false)
  const [explainSimple, setExplainSimple] = useState(false)

  async function handleSubmit(event) {
    event.preventDefault()
    setLoading(true)
    setError("")
    setSuccess("")
    setFallback(false)
    const form = new FormData(event.currentTarget)
    const symptoms = String(form.get("symptoms"))
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean)
    const payload = {
      symptoms,
      duration: form.get("duration"),
      age: Number(form.get("age")) || null,
    }
    try {
      const response = await api.post("/api/symptom-checker", payload)
      setResult(response.data)
      const riskResponse = await api.post("/api/emergency-risk", payload)
      setRisk(riskResponse.data)
      setSuccess("Symptom guidance generated by the backend AI placeholder.")
    } catch (err) {
      if (isBackendUnavailable(err)) {
        setFallback(true)
        setResult({
          possible_conditions: ["Common cold", "Fatigue", "Dehydration"],
          urgency: "low",
          recommendation: "Monitor symptoms and book a consultation if they persist.",
          disclaimer: "This AI output is for informational use only and is not a medical diagnosis.",
        })
        setRisk({
          ...emergencyRiskFallback,
          severity_level: symptoms.some((symptom) => ["chest pain", "shortness of breath", "fainting"].includes(symptom.toLowerCase()))
            ? "Emergency"
            : symptoms.length >= 3
              ? "Medium Risk"
              : "Low Risk",
          doctor_visit_priority: symptoms.length >= 3 ? "Medium" : "Low",
          suggested_specialist: "General Physician",
        })
        setSuccess("Backend unavailable, so mock symptom guidance is being shown.")
      } else {
        setError(getApiErrorMessage(err, "Symptom check failed. Please try again."))
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      <PageHeader
        eyebrow="Symptom intelligence"
        title="Check symptoms with AI guidance"
        description="Enter symptoms in everyday language and get structured, non-diagnostic guidance for what to do next."
      />

      <div className="mb-6">
        <RuralAccessibilityToolbar
          ruralMode={ruralMode}
          explainSimple={explainSimple}
          onToggleRural={() => setRuralMode((value) => !value)}
          onToggleExplain={() => setExplainSimple((value) => !value)}
        />
      </div>

      <div className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr]">
        <form onSubmit={handleSubmit} className={`panel animate-soft-in space-y-5 p-6 ${ruralMode ? "text-lg" : ""}`}>
          {error && <StatusMessage type="error" title="Symptom check failed">{error}</StatusMessage>}
          {success && <StatusMessage type={fallback ? "info" : "success"} title={fallback ? "Demo fallback active" : "AI guidance ready"}>{success}</StatusMessage>}
          <div>
            <label className="label">Symptoms</label>
            <textarea className="field mt-2 min-h-36" name="symptoms" defaultValue="fever, headache, sore throat" />
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="label">Duration</label>
              <select className="field mt-2" name="duration" defaultValue="2 days">
                <option>Less than 24 hours</option>
                <option>2 days</option>
                <option>3-7 days</option>
                <option>More than a week</option>
              </select>
            </div>
            <div>
              <label className="label">Age</label>
              <input className="field mt-2" name="age" type="number" defaultValue="32" min="1" />
            </div>
          </div>
          <button className="btn-primary w-full" type="submit" disabled={loading}>
            {loading ? <Loader2 className="animate-spin" size={20} /> : <Send size={20} />}
            {loading ? "Checking symptoms..." : "Run symptom check"}
          </button>
        </form>

        <section className="space-y-6">
          {risk && <RiskEngineCard risk={risk} ruralMode={ruralMode} explainSimple={explainSimple} />}

        <div className={`panel animate-soft-in p-6 ${ruralMode ? "text-lg" : ""}`}>
          <div className="flex items-center gap-3">
            <div className="grid h-12 w-12 place-items-center rounded-lg bg-mint text-teal-800">
              <Stethoscope size={24} />
            </div>
            <div>
              <h2 className="text-2xl font-bold">AI guidance</h2>
              <p className="text-sm text-slate-500">Placeholder output for demo use</p>
            </div>
          </div>

          {result ? (
            <div className="mt-6 space-y-5">
              <div className="rounded-lg bg-slate-50 p-5 shadow-inner">
                <p className="text-sm font-bold uppercase tracking-[0.18em] text-aqua">Urgency</p>
                <p className="mt-2 text-3xl font-black capitalize">{result.urgency}</p>
              </div>
              <div>
                <h3 className="font-bold">Possible conditions</h3>
                <div className="mt-3 flex flex-wrap gap-2">
                  {result.possible_conditions.map((condition) => (
                    <span key={condition} className="rounded-full bg-mint px-4 py-2 text-sm font-bold text-teal-800">{condition}</span>
                  ))}
                </div>
              </div>
              <p className={`rounded-lg border border-slate-200 p-4 text-slate-700 ${ruralMode ? "text-lg leading-8" : "leading-7"}`}>{result.recommendation}</p>
              {!!result.influencing_symptoms?.length && (
                <EvidencePanel
                  title="Symptoms that influenced recommendations"
                  items={result.influencing_symptoms}
                />
              )}
              {result.ai_reasoning_card && (
                <ReasoningCard card={result.ai_reasoning_card} />
              )}
              {!!result.trend_changes?.length && (
                <EvidencePanel title="History comparison" items={result.trend_changes} />
              )}
              <div className="flex gap-3 rounded-lg bg-amber-50 p-4 text-amber-900">
                <AlertCircle className="mt-0.5 shrink-0" size={20} />
                <p className="text-sm leading-6">{result.disclaimer}</p>
              </div>
            </div>
          ) : (
            <p className="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-6 text-slate-600">Symptom guidance will appear here after you run a check.</p>
          )}
        </div>
        </section>
      </div>
    </>
  )
}

function EvidencePanel({ title, items }) {
  return (
    <section className="rounded-lg border border-slate-200 bg-slate-50 p-4">
      <h3 className="font-bold">{title}</h3>
      <div className="mt-3 flex flex-wrap gap-2">
        {items.map((item) => (
          <span key={item} className="rounded-full bg-white px-3 py-1 text-sm font-bold text-slate-700 shadow-sm">{item}</span>
        ))}
      </div>
    </section>
  )
}

function ReasoningCard({ card }) {
  const rows = [
    ["Inputs considered", card.inputs_considered],
    ["Key findings", card.key_findings],
    ["Risk factors", card.risk_factors],
    ["Recommended specialist", [card.recommended_specialist]],
    ["Next action", [card.next_recommended_action]],
  ]

  return (
    <section className="rounded-lg border border-teal-200 bg-mint/60 p-4">
      <div className="flex items-center gap-2">
        <Brain className="text-teal-800" size={20} />
        <h3 className="font-black">AI reasoning card</h3>
        <span className="ml-auto rounded-full bg-white px-3 py-1 text-xs font-black text-teal-800">{card.confidence_score}% confidence</span>
      </div>
      <div className="mt-4 space-y-3">
        {rows.map(([label, values]) => (
          <div key={label}>
            <p className="text-xs font-black uppercase tracking-[0.14em] text-slate-500">{label}</p>
            <p className="mt-1 text-sm font-semibold leading-6 text-slate-700">{Array.isArray(values) ? values.join(", ") : values}</p>
          </div>
        ))}
      </div>
    </section>
  )
}
